builds:
-
  goos:
    - darwin
    - linux
    - windows
  env:
    - CGO_ENABLED=0
  main: cmd/clio/main.go

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
-
  name: homebrew-tap
  github:
    owner: markbates
    name: homebrew-tap
