before:
  hooks:
    - 'go mod tidy'
builds:
-
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - 386
    - arm
    - arm64
  goarm:
    - 6
    - 7
  env:
    - CGO_ENABLED=0
  main: ./cmd/clio/main.go
  binary: clio

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brew:
  name: clio
  github:
    owner: markbates
    name: homebrew-tap
  install: |
    bin.install "clio"

