before:
  hooks:
    - 'go mod tidy'
builds:
  -
    main: ./cmd/clio/main.go
    env:
      - CGO_ENABLED=0
archives:
  -
    replacements:
      '386': i386
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brew:
  name: 'clio'
  github:
    owner: 'markbates'
    name: 'homebrew-tap'
  install: |
    bin.install "clio"

