# This file was generated by GoReleaser. DO NOT EDIT.
class Clio < Formula
  desc ""
  homepage ""
  version "0.1.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/markbates/clio/releases/download/v0.1.5/clio_0.1.5_Darwin_x86_64.tar.gz"
    sha256 "4db8888d1b7531b85abf0c75ac407987e0466523c90383f83e46b0608c86c410"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/markbates/clio/releases/download/v0.1.5/clio_0.1.5_Linux_x86_64.tar.gz"
      sha256 "6527e88a92c47f3f48c046697626f0f56150e0f1a91f8f1b26bd559966fbd0be"
    end
  end

  def install
    bin.install "clio"
  end
end
