name: Release
on:
  push:
    branches:
      - master
    tags:
      -v1*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Release
      run: |
        echo ${{secrets.GITHUB_TOKEN}}
        go get github.com/markbates/pkger/cmd/pkger
        curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
        go install github.com/gobuffalo/release
        go mod tidy -v
        release doctor
        release -y -f version.go --skip-packr
